Add Github workflows and improve quality (#3)
* Update gitignore

* Add basic tests

* Add newline in pyresizer ascii logo

* Add basic CI pipeline

* Change name, update python version

* Add return() to functions

* Add new unit tests

* Update CI pipeline - add new stages

* Fix install packages step

* Fix unit tests command

* Update CI workflow

* Try to fix char error

* Revert "Try to fix char error"

This reverts commit 934a9c2d3e9afca41708de05cdeae7ac1ed73b9f.

* Try to force unicode for ascii

* Force encoding on stdout

* Add new features to CI workflow

* Add toml file and update code

* Change order in workflow

* Reorganize workflow

* Update resources

* Fix tests

* Format code; add linter checks

* Add new modules; update pipeline

* Add missing path

* Update project config; add new steps to ci pipeline

* Add missing package

* Remove unused imports

* Avoid duplicate output in pylint

* Make lines shorter in pyresizer

* Update workflow

* Fix syntax

* Improvements in workflows

* Reorganize workflows

* Fix input

* Define reusable workflow version

* Reorganize directory structure

* Remove branch refs

* Fix syntax

* Fix issues with env

* Add missing step

* Add new steps

* Update jobs

* Try to parametrise python version

* Try to use variables

* Try to add caching

* Update step

* Fix syntax

* Try to fix caching for binary

* Update job needs

* Upload/download artifact added

* Fix syntax

* Set retention time

* Fix path

* Add permissions to run

* Fix for missing chmod argument

* Simplify syntax

* Add CD workflow code

* Fix needs

* Migrate to pytest

* Update CI workflow

* Sort imports; update packages

* Update CD workflow

* Update e2e test path

* Change CWD

* Update e2e test path

* Update command in e2e

* Update path again

* Final fix for e2e tests

* Reorganize imports

* Update CI job syntax

* Add PR validation logic to CD pipeline

* Update CD triggers

* Fix nodejs code

* Update vars; disable push trigger

* Add missing needs

* Skip checks if not master - test

* Update branch name

* Update naming

* Update messages

* Again update messages and names

* Syntax error fix

* Add missing option to pyresizer

* Update syntax

* Update release workflow

* Fix needs in release workflow

* Fix for no labels

* Add if block

* Add missing step

* Fix variable

* Add missing esac word

* Update syntax in bash script

* Update bash script

* Add new stages to release pipeline

* Add / update release parameters

* Add tag parameter

* Update package process

* Fix root dir issues

* Update root dir again

* Enable features

* Update agents

* Update runer to ubuntu 22.04

* Update forgotten entry

* Update logic for resizing

* Update unittests for new logic

* Comment over CD pipeline

* Add e2e tests and resources

* Rewrite e2e tests to close files

* Fix platform issues in e2e tests

* Bump version, update readme, change default width

* Add missing blank line to git ignore

* Enable option to create release manually in case of issues

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,11 +7,145 @@ on:
       - 'master'
 
 jobs:
-  example:
-    name: Example
-    runs-on: "ubuntu-latest"
+  cd:
+    name: Call CD workflow
+    uses: ./.github/workflows/cd.yml
+
+  release:
+    name: Create release
+    runs-on: ubuntu-22.04
+    needs: cd
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
+      - name: Download artifact - Linux
+        uses: actions/download-artifact@v4
+        with:
+          path: binaries
+
+      - name: List artifacts
+        run: ls -la binaries
+
+      - name: Get latest PR id
+        id: latestpr
+        run: |
+          #!/usr/bin/env bash
+          set -xeu -o pipefail
+
+          LATEST_PR_ID=$(git log --grep="Merge pull request #[0-9]\+" --pretty=oneline -1 | sed -En "s/.*#([[:digit:]]+).*/\1/p";)
+          if [[ -z $LATEST_PR_ID ]]; then
+            echo "ERROR: Unable to find latest PR id!"
+            exit 101
+          fi
+          echo "Saving LATEST_PR_ID to Github variables..."
+          echo "latest_pr_id=${LATEST_PR_ID}" >> "$GITHUB_OUTPUT"
+
+      - name: Get release type
+        uses: actions/github-script@v7
+        id: releasetype
+        with:
+          script: |
+            const prId = ${{ steps.latestpr.outputs.latest_pr_id }};
+            const { owner, repo } = context.repo;
+
+            const { data: pr } = await github.rest.issues.get({
+              owner,
+              repo,
+              issue_number: parseInt(prId, 10)
+            });
+
+            const validLabels = ["major", "minor", "patch"];
+            const labels = pr.labels.map(label => label.name.toLowerCase()) || [];
+
+            const matchingLabels = labels.filter(label => validLabels.includes(label));
+
+            let releaseTypeCheckResult = null;
+            let releaseTypeCheckMessage = null;
+
+            if (matchingLabels.length === 0) {
+              releaseTypeCheckResult = 'failure';
+              releaseTypeCheckMessage = `PR must contain exactly one of the required labels: (${validLabels.join(', ')}). ❌`;
+            } else if (matchingLabels.length > 1) {
+              releaseTypeCheckResult = 'failure';
+              releaseTypeCheckMessage = `PR contains multiple valid labels: (${matchingLabels.join(', ')}). Only one is allowed. ❌`;
+            } else {
+              releaseTypeCheckResult = 'success';
+              releaseTypeCheckMessage = `PR contains exactly one valid label: ${matchingLabels[0]} ✅`;
+            }
+
+            console.log(`${releaseTypeCheckMessage}`);
+            if (`${releaseTypeCheckResult}` !== 'success') core.setFailed(`${releaseTypeCheckMessage}`);
+            core.setOutput("pr_label", matchingLabels[0]);
+
+      - name: Calculate new tag
+        id: calculatetag
+        run: |
+          #!/usr/bin/env bash
+          set -xeu -o pipefail
+
+          # Convert to lower case
+          RELEASE_TYPE=$(echo ${{ steps.releasetype.outputs.pr_label }} | tr '[:upper:]' '[:lower:]')
+          PREFIXED_TAG=false
+          if [[ -z $RELEASE_TYPE ]]; then
+            echo "ERROR: Unable to determine release type!"
+            exit 101
+          fi
+
+          mapfile CURRENT_TAGS < <(git tag --sort=-v:refname)
+
+          if [[ ${#CURRENT_TAGS[@]} == 0 ]]; then
+            echo "No tags found, creating initial tag: v1.0.0"
+            NEW_TAG='v1.0.0'
+          else
+            echo "Following tags were found: " "${CURRENT_TAGS[@]}"
+            echo "Latest tag is: ${CURRENT_TAGS[0]}"
+            latest_tag=${CURRENT_TAGS[0]}
+            if [[ $latest_tag == v* ]]; then
+              echo "Tag prefixed with 'v', removing prefix temporary"
+              latest_tag=${CURRENT_TAGS[0]#v}
+              PREFIXED_TAG=true
+            fi
+            IFS='.' read -r major minor patch <<< "$latest_tag"
+            next_major_version="$((major + 1)).0.0"
+            next_minor_version="${major}.$((minor + 1)).0"
+            next_patch_version="${major}.${minor}.$((patch + 1))"
+            case "$RELEASE_TYPE" in
+              "major") NEW_TAG=$next_major_version ;;
+              "minor") NEW_TAG=$next_minor_version ;;
+              "patch") NEW_TAG=$next_patch_version ;;
+              *) echo "Unknow release type ${RELEASE_TYPE}" && exit 102
+            esac
+          fi
+          if [[ "$PREFIXED_TAG" == true ]]; then
+              NEW_TAG="v${NEW_TAG}"
+          fi
+          echo "New tag to be created: ${NEW_TAG}"
+          echo "Saving NEW_TAG to Github variables..."
+          echo "new_tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"
+
+      - name: Create packages
+        run: |
+          #!/usr/bin/env bash
+          set -xeu -o pipefail
+
+          NEW_TAG=${{ steps.calculatetag.outputs.new_tag }}
+          ROOT_DIR=$PWD
+          cp README.md binaries/pyresizer-binary-Linux/
+          cp README.md binaries/pyresizer-binary-Windows/
+          echo "Create Linux release..."
+          cd "${ROOT_DIR}/binaries/pyresizer-binary-Linux/" && tar -cvf "pyresizer-${NEW_TAG}-linux-x64.tar" ./* && mv ./*.tar "${ROOT_DIR}/"
+          echo "Create Windows release..."
+          cd "${ROOT_DIR}/binaries/pyresizer-binary-Windows/" && zip -vr "pyresizer-${NEW_TAG}-windows-x64.zip" ./* && mv ./*.zip "${ROOT_DIR}/"
+
+      - name: Create Github release
+        uses: ncipollo/release-action@v1
+        with:
+          artifacts: "pyresizer-${{ steps.calculatetag.outputs.new_tag }}-linux-x64.tar,pyresizer-${{ steps.calculatetag.outputs.new_tag }}-windows-x64.zip"
+          body: "New release ${{ steps.calculatetag.outputs.new_tag }}"
+          generateReleaseNotes: true
+          commit: ${{ github.sha }}
+          name: ${{ steps.calculatetag.outputs.new_tag }}
+          tag: ${{ steps.calculatetag.outputs.new_tag }}
